<a href="https://colab.research.google.com/github/Son-mideok/e-Learning/blob/main/221111_2%EA%B0%95_%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC_%EA%B8%B0%EC%B4%88_%ED%86%A0%ED%81%AC%EB%82%98%EC%9D%B4%EC%A7%95%EA%B3%BC_%EC%9B%90%ED%95%AB%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 자연어 처리 기초 - 토크나이징과 원핫인코딩


In [2]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import nltk

In [5]:
nltk.download("all", quiet=True)

True

## 단어 단위 Tokenizing

In [6]:
from nltk.tokenize import word_tokenize
text = "Friends, Fomans, Countrymen, lend me your ears:."
print(word_tokenize(text))

['Friends', ',', 'Fomans', ',', 'Countrymen', ',', 'lend', 'me', 'your', 'ears', ':', '.']


## 문장 단위 Tokenizing

In [7]:
from nltk.tokenize import sent_tokenize
text = "Natural language processing (NLP) is a subfield of \
linguistics, computer science, and artificial intelligence \
concerned with the interactions between computers and human language, \
in particular how to program computers to process and analyze large \
amounts of natural language data. The goal is a computer capable of \
understanding the contents of documents, including the contextual \
nuances of the language within them. The technology can then accurately \
extract information and insights contained in the documents as well as categorize and organize the documents themselves."

print(sent_tokenize(text))

['Natural language processing (NLP) is a subfield of linguistics, computer science, and artificial intelligence concerned with the interactions between computers and human language, in particular how to program computers to process and analyze large amounts of natural language data.', 'The goal is a computer capable of understanding the contents of documents, including the contextual nuances of the language within them.', 'The technology can then accurately extract information and insights contained in the documents as well as categorize and organize the documents themselves.']


## One-hot Encoding 적용하기

In [8]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [9]:
# 원핫 인코딩을 적용할 예제 데이터를 설정
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold','warm','hot']
print(set(data))
values = array(data)
print(values)

{'warm', 'hot', 'cold'}
['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


In [10]:
# Integer Encoding 진행
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


In [11]:
# One-hot Encoding 진행
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print(integer_encoded.reshape(len(integer_encoded), 1))
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [14]:
# One-hot Encoding 적용할 예제를 다시 string 형태로 변경
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold']
